<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Call to Action', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"elementId":"guten-OqBJa3","background":{"type":"default","image":{"Desktop":{"id":26,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/action-african-american-african-descent-agreement-american-black-1448527-pxhere.com_.webp","width":1920,"height":1092,"altOriginal":"action african american african descent agreement american black"}},"position":{"Desktop":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-black-tertiary"}},"opacity":"0.8","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-PF1k7w","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-OBWF5r","content":"Need Financial Advisor For Your Business? Contact Us Today","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-2ST0Pm","alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"20","bottom":"","left":"20"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"8","bottom":"0","left":"8"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat dolore magna</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-W19JFe","content":"Contact Us","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"gv-color-primary"},"ariaLabel":"Direct to contact"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
