<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Title', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170","Tablet":""},"gap":"no","elementId":"guten-uL3WNu","background":{"type":"default","color":"","image":{"Desktop":{"id":74,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/achievement-analysis-brainstorming-business-business-plan-caucasian-1448601-pxhere.com_.jpg"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-black-tertiary"}},"opacity":"0.88","margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"260","bottom":"260"}},"Tablet":{"unit":"px","dimension":{"left":"20","right":"20","top":"160","bottom":"160"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"","left":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-Tf7s4t"} -->
<!-- wp:gutenverse/heading {"elementId":"guten-Brygum","content":"Page Not Found","type":1,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"h2-hero-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"40"},"Mobile":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":[],"Mobile":[]}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Lundfa","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:paragraph -->
<p>It looks like nothing was found at this location. Maybe try a search?</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/search {"elementId":"guten-dVOUjq","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"inputPlaceholder":"Search Here","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[],"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"0"}}},"inputHeight":{"Desktop":"56"},"inputWidth":{"Desktop":{"unit":"%","point":"60"},"Tablet":{"unit":"%","point":"70"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}},"alignContent":{"Desktop":"center"}} -->
<!-- wp:gutenverse/button {"elementId":"guten-rScIJ0","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100"},"paddingButton":{"Desktop":[],"Mobile":[]},"buttonBackground":{"color":{"type":"variable","id":"gv-color-primary"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"gv-color-white"},"iconLineHeight":true} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
