<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Content', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-2cw8B7","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"0","left":"10"}}},"zIndex":{"Desktop":"2"},"wrapColumn":{"Desktop":false,"Tablet":true,"Mobile":true}} -->
<div class="section-wrapper" data-id="2cw8B7"><section class="wp-block-gutenverse-section guten-element guten-section guten-2cw8B7 layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-tCwytO","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"140","top":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-tCwytO"><div class="guten-column-wrapper" data-id="tCwytO"><!-- wp:gutenverse/heading {"elementId":"guten-aMPUWb","type":5,"textAlign":{"Desktop":"left","Tablet":"left","Mobile":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-aMPUWb animated guten-element-hide desktop-fadeInLeft">Contact Us</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-3kS4kk","color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-3kS4kk animated guten-element-hide desktop-fadeInLeft">Get In Touch With Us</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-bwmK4G","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-bwmK4G animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-7z09Io","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="7z09Io"><section class="wp-block-gutenverse-section guten-element guten-section guten-7z09Io layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-Ol0DVU"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Ol0DVU"><div class="guten-column-wrapper" data-id="Ol0DVU"><!-- wp:gutenverse/icon-box {"elementId":"guten-7MwyZd","separateButtonLink":false,"title":"Kuta, Bali","titleTag":"h3","description":"Jl. Sunset Road No.815","icon":"gtn gtn-apartment-light","iconSize":{"Desktop":40,"Mobile":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":[]},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}},"Mobile":[],"Tablet":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"parentSelector":".guten-7MwyZd:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-7MwyZd guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-apartment-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Kuta, Bali</h3><p class="icon-box-description">Jl. Sunset Road No.815</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-ry5osU","margin":{"Tablet":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ry5osU"><div class="guten-column-wrapper" data-id="ry5osU"><!-- wp:gutenverse/icon-box {"elementId":"guten-nQqKlc","separateButtonLink":false,"title":"Denpasar, Bali","titleTag":"h3","description":"Jl. Raya Puputan No 125","icon":"gtn gtn-cityscape-light","iconSize":{"Desktop":40,"Mobile":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":[]},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}},"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"parentSelector":".guten-nQqKlc:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-nQqKlc guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-cityscape-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Denpasar, Bali</h3><p class="icon-box-description">Jl. Raya Puputan No 125</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-k5uquA","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="k5uquA"><section class="wp-block-gutenverse-section guten-element guten-section guten-k5uquA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-lQPNC0"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-lQPNC0"><div class="guten-column-wrapper" data-id="lQPNC0"><!-- wp:gutenverse/icon-box {"elementId":"guten-HE6K3N","separateButtonLink":false,"title":"Phone Call","titleTag":"h3","description":"(021) 231 - 2826","icon":"gtn gtn-phone1-light","iconSize":{"Desktop":40,"Mobile":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":[]},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}},"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"parentSelector":".guten-HE6K3N:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-HE6K3N guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Phone Call</h3><p class="icon-box-description">(021) 231 - 2826</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-47yyzn","margin":{"Tablet":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-47yyzn"><div class="guten-column-wrapper" data-id="47yyzn"><!-- wp:gutenverse/icon-box {"elementId":"guten-TTPwcH","separateButtonLink":false,"title":"Send Us A Message","titleTag":"h3","description":"support@domain.com","icon":"gtn gtn-email1-light","iconSize":{"Desktop":40,"Mobile":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]},"iconMargin":{"Desktop":[],"Mobile":[]},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}},"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"parentSelector":".guten-TTPwcH:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-TTPwcH guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-email1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Send Us A Message</h3><p class="icon-box-description">support@domain.com</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-CWslS9","background":{"type":"default","color":{"type":"variable","id":"theme-4"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"color":{"r":5,"g":5,"b":5,"a":0.08},"horizontal":"0","vertical":"5","blur":"30"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"60","left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"zIndex":{"Desktop":"5"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-CWslS9 animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="CWslS9"><!-- wp:gutenverse/form-builder {"elementId":"guten-TZtAs1","margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"2"}} -->
<form style="display:none" class="guten-element guten-form-builder guten-TZtAs1"><!-- wp:gutenverse/form-input-text {"elementId":"guten-3bX8Ol","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperColor":{"Desktop":[]},"helperPadding":{"Desktop":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"meta-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-1"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-8"}}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-3bX8Ol hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-email {"elementId":"guten-oXyIca","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"meta-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-1"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","color":{"type":"variable","id":"theme-8"},"width":"1"}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-oXyIca hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-pK01mc","showLabel":false,"inputPlaceholder":"Your Subject","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"meta-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-1"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","color":{"type":"variable","id":"theme-8"},"width":"1"}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-pK01mc hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-aM3jG3","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"inputHeight":{"Desktop":"160"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"meta-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-1"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","color":{"type":"variable","id":"theme-8"},"width":"1"}},"inputBorderHover":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-aM3jG3 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-8fxoMT","content":"Send Message","buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-11"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":""},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"button-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"theme-4"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":[]}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-8fxoMT"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Message</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --><!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-HrmcEJ","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}},"zIndex":{"Desktop":""}} -->
<div class="section-wrapper" data-id="HrmcEJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-HrmcEJ layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-q3lgRr","margin":{"Desktop":{"unit":"px","dimension":{"top":"-80","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"-120"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Desktop":""}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-q3lgRr"><div class="guten-column-wrapper" data-id="q3lgRr"><!-- wp:gutenverse/google-maps {"elementId":"guten-oGEFfX","location":"Jl. Sunset Road, Bali","zoom":"17","height":{"Desktop":"460"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-10"}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":"1"}} -->
<div class="guten-element gutenverse-maps guten-oGEFfX"><iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=Jl.%20Sunset%20Road%2C%20Bali&amp;z=17&amp;t=m&amp;output=embed&amp;iwloc=near" title="Jl. Sunset Road, Bali"></iframe></div>
<!-- /wp:gutenverse/google-maps --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
