<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Feature', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-uL3WNu","background":{"type":"default","color":"","image":{"Desktop":{"id":74,"image":"' . esc_url( FINANCIO_URI ) . 'assets/img/achievement-analysis-brainstorming-business-business-plan-caucasian-1448601-pxhere.com.jpg"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-6"}},"opacity":"0.8","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"80"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20","right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"","right":"","left":""}}}} -->
<div class="section-wrapper" data-id="uL3WNu"><section class="wp-block-gutenverse-section guten-element guten-section guten-uL3WNu layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-Tf7s4t"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Tf7s4t"><div class="guten-column-wrapper" data-id="Tf7s4t"><!-- wp:gutenverse/heading {"elementId":"guten-VibiRx","type":5,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-VibiRx animated guten-element-hide desktop-fadeInUp">Our Service</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-gFYC7c","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"left"},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-gFYC7c animated guten-element-hide desktop-fadeInUp">What Service We Offer</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-3RPwN7","alignment":{"Desktop":"center","Tablet":"center","Mobile":"left"},"textColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"26","left":"26"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"12","bottom":"0","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-3RPwN7 animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-2IMNVq","margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<div class="section-wrapper" data-id="2IMNVq"><section class="wp-block-gutenverse-section guten-element guten-section guten-2IMNVq slow layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-XBu5sY","margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-XBu5sY"><div class="guten-column-wrapper" data-id="XBu5sY"><!-- wp:gutenverse/icon-box {"elementId":"guten-9Xt3hx","title":"Investment Planning","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-invest-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-4"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"parentSelector":".guten-9Xt3hx:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-9Xt3hx animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-invest-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Investment Planning</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-F9jDe9","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"parentSelector":".guten-9Xt3hx:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-F9jDe9"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-PFbrIW","margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PFbrIW"><div class="guten-column-wrapper" data-id="PFbrIW"><!-- wp:gutenverse/icon-box {"elementId":"guten-CHNSY2","title":"Audit \u0026 Assurance","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-consut2-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-4"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"parentSelector":".guten-CHNSY2:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-CHNSY2 animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-consut2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Audit & Assurance</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-9MhRQl","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"parentSelector":".guten-CHNSY2:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-9MhRQl"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-wgjxWE","margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wgjxWE"><div class="guten-column-wrapper" data-id="wgjxWE"><!-- wp:gutenverse/icon-box {"elementId":"guten-jR8kCP","title":"Business Taxation","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-business-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-4"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"parentSelector":".guten-jR8kCP:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-jR8kCP animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-business-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Business Taxation</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-rkHzRF","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"parentSelector":".guten-jR8kCP:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-rkHzRF"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-z6ZvzV","margin":{"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"-80"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"-40","left":"0"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<div class="section-wrapper" data-id="z6ZvzV"><section class="wp-block-gutenverse-section guten-element guten-section guten-z6ZvzV slow layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-SENnBD","margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-SENnBD"><div class="guten-column-wrapper" data-id="SENnBD"><!-- wp:gutenverse/icon-box {"elementId":"guten-Yozt5j","title":"Accounts Outsourcing","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-coins-1-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-4"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"},"parentSelector":".guten-Yozt5j:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-Yozt5j animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-coins-1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Accounts Outsourcing</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-VpKUAo","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"parentSelector":".guten-Yozt5j:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-VpKUAo"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-pye0x1","margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-pye0x1"><div class="guten-column-wrapper" data-id="pye0x1"><!-- wp:gutenverse/icon-box {"elementId":"guten-STFGXb","title":"Payroll \u0026 Salary","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-commerce-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-4"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"color":{"r":16,"g":16,"b":16,"a":0.1},"horizontal":"0","vertical":"3","blur":"15","spread":"0"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInUp"},"delay":"800","duration":"normal"},"parentSelector":".guten-STFGXb:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-STFGXb animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-commerce-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Payroll & Salary</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-WfGJxZ","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"parentSelector":".guten-STFGXb:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-WfGJxZ"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-cPlXht","margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cPlXht"><div class="guten-column-wrapper" data-id="cPlXht"><!-- wp:gutenverse/icon-box {"elementId":"guten-B4VTaV","title":"Loan Management","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-loan-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-4"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"theme-4"},"iconBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"},"parentSelector":".guten-B4VTaV:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-B4VTaV animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-loan-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Loan Management</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-HPkW4A","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"parentSelector":".guten-B4VTaV:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-HPkW4A"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
