<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Team', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"elementId":"guten-jE5fRc","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
<div class="section-wrapper" data-id="jE5fRc"><section class="wp-block-gutenverse-section guten-element guten-section guten-jE5fRc layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-KhvMhz","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KhvMhz"><div class="guten-column-wrapper" data-id="KhvMhz"><!-- wp:gutenverse/heading {"elementId":"guten-dbmFbD","type":5,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"h5-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-dbmFbD animated guten-element-hide desktop-fadeInUp">Our Team</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-bsCdV0","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-bsCdV0 animated guten-element-hide desktop-fadeInUp">Meet With Professional Team</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-0vkpId","alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"26","left":"26"}},"Tablet":{"unit":"%","dimension":{"right":"12","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-0vkpId animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-3FX1Y1","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<div class="section-wrapper" data-id="3FX1Y1"><section class="wp-block-gutenverse-section guten-element guten-section guten-3FX1Y1 slow layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null,"Tablet":null},"elementId":"guten-lSYSih","margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-lSYSih"><div class="guten-column-wrapper" data-id="lSYSih"><!-- wp:gutenverse/team {"elementId":"guten-sncPyv","profileType":"overlay","overlayPosition":"bottom","src":{"id":90,"image":"' . esc_url( FINANCIO_URI ) . 'assets/img/laptop-notebook-work-hand-suit-people-1278242-pxhere.com.jpg"},"name":"Jennifer Doe","job":"Financial Advisor","nameColor":{"type":"variable","id":"theme-4"},"nameTypography":{"type":"variable","id":"h3-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"jobColor":{"type":"variable","id":"theme-4"},"jobTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"30","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":[]},"hoverMargin":{"Desktop":[]},"hoverBgColor":{"type":"variable","id":"ninth"},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-sncPyv animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( FINANCIO_URI ) . 'assets/img/laptop-notebook-work-hand-suit-people-1278242-pxhere.com.jpg" alt="Jennifer Doe"/><div class="profile-body bottom"><h3 class="profile-title " aria-label="Profile Name">Jennifer Doe</h3><p class="profile-sub" aria-label="Profile Job">Financial Advisor</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-LvGJKL","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"16","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"theme-4"},"bgColor":{"type":"variable","id":"theme-0"},"itemPadding":{"Desktop":[]},"hoverIconColor":{"type":"variable","id":"theme-0"},"hoverBgColor":{"type":"variable","id":"theme-4"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-LvGJKL circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-lxf3Sv"} -->
<div class="guten-element guten-social-icon guten-lxf3Sv facebook"><a id="guten-lxf3Sv"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-jSL3O7"} -->
<div class="guten-element guten-social-icon guten-jSL3O7 twitter"><a id="guten-jSL3O7"><i class="fab fa-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-hQNLcK"} -->
<div class="guten-element guten-social-icon guten-hQNLcK instagram"><a id="guten-hQNLcK"><i class="gtn gtn-instagram-1-light"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null,"Tablet":null},"elementId":"guten-QugB45","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QugB45"><div class="guten-column-wrapper" data-id="QugB45"><!-- wp:gutenverse/team {"elementId":"guten-DQMxmt","profileType":"overlay","overlayPosition":"bottom","src":{"id":98,"image":"' . esc_url( FINANCIO_URI ) . 'assets/img/suit-formal-wear-tuxedo-fashion-groom-outerwear-1545637-pxhere.com.jpg"},"name":"Jonathan Doe","job":"Financial Advisor","nameColor":{"type":"variable","id":"theme-4"},"nameTypography":{"type":"variable","id":"h3-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"jobColor":{"type":"variable","id":"theme-4"},"jobTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"30","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}},"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"type":"variable","id":"ninth"},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-DQMxmt animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( FINANCIO_URI ) . 'assets/img/suit-formal-wear-tuxedo-fashion-groom-outerwear-1545637-pxhere.com.jpg" alt="Jonathan Doe"/><div class="profile-body bottom"><h3 class="profile-title " aria-label="Profile Name">Jonathan Doe</h3><p class="profile-sub" aria-label="Profile Job">Financial Advisor</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-9hrXzV","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"16","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"theme-4"},"bgColor":{"type":"variable","id":"theme-0"},"itemPadding":{"Desktop":[]},"hoverIconColor":{"type":"variable","id":"theme-0"},"hoverBgColor":{"type":"variable","id":"theme-4"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-9hrXzV circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-WeoRYA"} -->
<div class="guten-element guten-social-icon guten-WeoRYA facebook"><a id="guten-WeoRYA"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-kBOxHe"} -->
<div class="guten-element guten-social-icon guten-kBOxHe twitter"><a id="guten-kBOxHe"><i class="fab fa-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-92PIgK"} -->
<div class="guten-element guten-social-icon guten-92PIgK instagram"><a id="guten-92PIgK"><i class="gtn gtn-instagram-1-light"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null,"Tablet":null},"elementId":"guten-ctSVFF","margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ctSVFF"><div class="guten-column-wrapper" data-id="ctSVFF"><!-- wp:gutenverse/team {"elementId":"guten-Chanoy","profileType":"overlay","overlayPosition":"bottom","src":{"id":97,"image":"' . esc_url( FINANCIO_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com.jpg"},"name":"Nelly Cooper","job":"Financial Advisor","nameColor":{"type":"variable","id":"theme-4"},"nameTypography":{"type":"variable","id":"h3-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"jobColor":{"type":"variable","id":"theme-4"},"jobTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"descColor":{"type":"variable","id":"fifth"},"descTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"30","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverBgColor":{"type":"variable","id":"ninth"},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-Chanoy animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( FINANCIO_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com.jpg" alt="Nelly Cooper"/><div class="profile-body bottom"><h3 class="profile-title " aria-label="Profile Name">Nelly Cooper</h3><p class="profile-sub" aria-label="Profile Job">Financial Advisor</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-6lqnxl","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"16","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"theme-4"},"bgColor":{"type":"variable","id":"theme-0"},"itemPadding":{"Desktop":[]},"hoverIconColor":{"type":"variable","id":"theme-0"},"hoverBgColor":{"type":"variable","id":"theme-4"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-6lqnxl circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-rBHf4F"} -->
<div class="guten-element guten-social-icon guten-rBHf4F facebook"><a id="guten-rBHf4F"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-ga3LEQ"} -->
<div class="guten-element guten-social-icon guten-ga3LEQ twitter"><a id="guten-ga3LEQ"><i class="fab fa-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-Z2k9u7"} -->
<div class="guten-element guten-social-icon guten-Z2k9u7 instagram"><a id="guten-Z2k9u7"><i class="gtn gtn-instagram-1-light"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
