<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Title', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-uL3WNu","background":{"type":"default","color":"","image":{"Desktop":{"id":74,"image":"' . esc_url( FINANCIO_URI ) . 'assets/img/achievement-analysis-brainstorming-business-business-plan-caucasian-1448601-pxhere.com.jpg"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-6"}},"opacity":"0.88","margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"260","bottom":"260"}},"Tablet":{"unit":"px","dimension":{"left":"20","right":"20","top":"160","bottom":"160"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"","left":""}}}} -->
<div class="section-wrapper" data-id="uL3WNu"><section class="wp-block-gutenverse-section guten-element guten-section guten-uL3WNu layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-Tf7s4t"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Tf7s4t"><div class="guten-column-wrapper" data-id="Tf7s4t"><!-- wp:gutenverse/heading {"elementId":"guten-Brygum","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"h2-hero-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"40"},"Mobile":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-Brygum">Page Not Found</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Lundfa","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element gutenverse-text-editor guten-Lundfa"><div class="text-content-inner"><!-- wp:paragraph -->
<p>It looks like nothing was found at this location. Maybe try a search?</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/search {"elementId":"guten-dVOUjq","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputPlaceholder":"Search Here","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[],"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"0"}}},"inputHeight":{"Desktop":"56"},"inputWidth":{"Desktop":{"unit":"%","point":"60"},"Tablet":{"unit":"%","point":"70"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"body-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}},"alignContent":{"Desktop":"center"}} -->
<div class="guten-element guten-dVOUjq guten-search"><form class="gutenverse-search-form"><div class="search-input-container"><input type="search" placeholder="Search Here" name="s" class="gutenverse-search gutenverse-search-input"/></div><!-- wp:gutenverse/button {"elementId":"guten-rScIJ0","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100"},"paddingButton":{"Desktop":[],"Mobile":[]},"buttonBackground":{"color":{"type":"variable","id":"theme-0"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-11"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"button-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"theme-4"},"iconLineHeight":true} -->
<div class="guten-element guten-button-wrapper guten-rScIJ0"><button class="guten-button guten-button-xs" type="submit"><span>Search</span></button></div>
<!-- /wp:gutenverse/button --></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
