<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Description', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-hWOsrW","verticalAlign":"center","background":{"type":"default","color":"","videoPlayOnMobile":false},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"100","left":"20","right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"100","left":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100},"sectionVerticalAlign":"center","elementId":"guten-lTdEKL","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":"70"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-B5Pvel","content":"Who We Are","type":5,"color":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-LxkPRr","content":"We Keep Your Finance Safe And Ensure High Availability","color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Tablet":{"unit":"px","dimension":{"right":"80"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-mWWWOZ","textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-Z3dpAf","title":"Investment Planning","percentage":90,"barColor":{"type":"variable","id":"gv-color-background-tertiary"},"trackColor":{"type":"variable","id":"gv-color-primary"},"trackHeight":{"Desktop":"12"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"percentColor":{"type":"variable","id":"gv-color-text-secondary"},"percentTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-We5WqD","title":"Accounts Outsourcing","percentage":92,"barColor":{"type":"variable","id":"gv-color-background-tertiary"},"trackColor":{"type":"variable","id":"gv-color-primary"},"trackHeight":{"Desktop":"12"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"percentColor":{"type":"variable","id":"gv-color-text-secondary"},"percentTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-2epFBl","title":"Business Taxation","percentage":91,"barColor":{"type":"variable","id":"gv-color-background-tertiary"},"trackColor":{"type":"variable","id":"gv-color-primary"},"trackHeight":{"Desktop":"12"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"percentColor":{"type":"variable","id":"gv-color-text-secondary"},"percentTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-5tnlk8","title":"Payroll \u0026 Salary","percentage":89,"barColor":{"type":"variable","id":"gv-color-background-tertiary"},"trackColor":{"type":"variable","id":"gv-color-primary"},"trackHeight":{"Desktop":"12"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"percentColor":{"type":"variable","id":"gv-color-text-secondary"},"percentTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[]}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-KpeFEu","background":{"type":"default","image":{"Desktop":{"id":31,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/action-american-beverage-brainstorming-business-caucasian-1445431-pxhere.com_.webp","width":1920,"height":1280,"altOriginal":"action american beverage brainstorming business caucasian"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"unit":"px","point":""}},"yposition":{"Desktop":{"point":"","unit":"px"}},"repeat":{"Desktop":"no-repeat"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"60"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-9eGLMg","space":{"Desktop":{"point":"488","unit":"px"},"Mobile":{"point":"321","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
