<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Footer', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"elementId":"guten-Jmjnhj","verticalAlign":"center","background":{"type":"default","color":{"type":"variable","id":"gv-color-text-primary"},"videoPlayOnMobile":false},"topDivider":{"type":"mountains","width":{"Desktop":"125","Tablet":"168","Mobile":"245"},"height":{"Desktop":"115","Tablet":"102","Mobile":"91"},"color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px"},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"0","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"10","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"10","left":"10","right":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"sectionVerticalAlign":"center","elementId":"guten-HTkVBY","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-i2cooj","margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-l03XgJ","margin":{"Tablet":{"unit":"px","dimension":{"top":"-20","right":"","bottom":"","left":""}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]}} -->
<!-- wp:gutenverse/image {"elementId":"guten-ITwWw1","imgSrc":{"media":{"imageId":39,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-financio-white.webp","orientation":"landscape"},"medium":{"height":70,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-financio-white.webp","orientation":"landscape"},"large":{"height":238,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-financio-white.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-financio-white.webp","height":313,"width":1345,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"logo financio white","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"75"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Mobile":{"radius":[]}},"align":{"Desktop":"left"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"ariaLabel":"direct to home","imageLoad":"eager"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-EGZWn0","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left","Tablet":"left","Mobile":"left"},"textColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}}}} -->
<!-- wp:paragraph -->
<p><meta charset="utf-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/social-icons {"elementId":"guten-OEGrrD","iconSize":{"Desktop":{"point":"16","unit":"px"}},"gap":{"Desktop":"18","Tablet":"10","Mobile":"10"},"alignment":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"type":"variable","id":"gv-color-primary"},"border":{"radius":{"Desktop":{"unit":"px"}}},"itemPadding":{"unit":"px"},"hoverIconColor":{"type":"variable","id":"gv-color-primary"},"hoverBgColor":{"type":"variable","id":"gv-color-white"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px"}}} -->
<!-- wp:gutenverse/social-icon {"elementId":"guten-EF8aJF","url":"#","ariaLabel":"Follow twitter","icon":"fab fa-x-twitter","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTM4OS4yIDQ4aDcwLjZMMzA1LjYgMjI0LjIgNDg3IDQ2NEgzNDVMMjMzLjcgMzE4LjYgMTA2LjUgNDY0SDM1LjhMMjAwLjcgMjc1LjUgMjYuOCA0OEgxNzIuNEwyNzIuOSAxODAuOSAzODkuMiA0OHpNMzY0LjQgNDIxLjhoMzkuMUwxNTEuMSA4OGgtNDJMMzY0LjQgNDIxLjh6Ii8+PC9zdmc+","text":"","iconSize":{"Desktop":{"point":"","unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-1JX5lj","url":"#","ariaLabel":"Follow facebook","icon":"gtn gtn-facebook-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yNCAwLjQwNmgtNC4xNTZxLTEuNzUgMC0zLjE1NiAwLjU2My0xLjQzOCAwLjUzMS0yLjQzOCAxLjU2M3QtMS41MzEgMi41cS0wLjUzMSAxLjQzOC0wLjUzMSAzLjI1djMuNjI1aC00LjE4OHEtMC4yODEgMC0wLjQ2OSAwLjE4OHQtMC4xODggMC40Njl2NS4yNXEwIDAuMjgxIDAuMTg4IDAuNDY5dDAuNDY5IDAuMTg4aDQuMTg4djEzLjI4MXEwIDAuMjgxIDAuMTg4IDAuNDY5dDAuNDM4IDAuMTg4aDUuNDY5cTAuMjUgMCAwLjQ1My0wLjE4OHQwLjIwMy0wLjQ2OXYtMTMuMjgxaDQuODc1cTAuMjUgMCAwLjQ1My0wLjE4OHQwLjIwMy0wLjQ2OXYtNS4yNXEwLTAuMTI1LTAuMDYzLTAuMjV0LTAuMTU2LTAuMjE5cS0wLjA2My0wLjA5NC0wLjE4OC0wLjE0MXQtMC4yNS0wLjA0N2gtNC44NzV2LTMuMDYzcTAtMS4xMjUgMC40MDYtMS42ODh0MS44NDQtMC41NjNoMi44MTNxMC4yODEgMCAwLjQ2OS0wLjE4OHQwLjE4OC0wLjQ2OXYtNC44NzVxMC0wLjI4MS0wLjE4OC0wLjQ2OXQtMC40NjktMC4xODh2MHoiPjwvcGF0aD4KPC9zdmc+Cg==","text":"","iconSize":{"Desktop":{"point":"","unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-WNkthn","url":"#","ariaLabel":"Follow youtube","icon":"gtn gtn-youtube-v-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0zMS40MzggOC44NDRxLTAuMjgxLTEuMjgxLTEuMjM0LTIuMTQxdC0yLjIwMy0xLjAxNnEtMS41LTAuMTU2LTMtMC4yNXQtMy0wLjE0MS0zLTAuMDQ3aC02dC0zIDAuMDQ3LTMgMC4xNDEtMi45NjkgMC4yNXEtMS4yODEgMC4xNTYtMi4yMzQgMS4wMTZ0LTEuMjM0IDIuMTQxcS0wLjQwNiAxLjgxMy0wLjQ4NCAzLjc1dC0wLjA3OCAzLjgxMyAwLjA2MyAzLjgxMyAwLjUgMy43NXEwLjI4MSAxLjI4MSAxLjIzNCAyLjE0MXQyLjIzNCAwLjk4NHExLjQ2OSAwLjE4OCAyLjk2OSAwLjI4MXQzIDAuMTI1IDMgMC4wMzFxMS41IDAuMDMxIDMgMC4wMzF0My0wLjAzMXExLjUgMCAzLTAuMDMxdDMtMC4xMjUgMi45NjktMC4yODFxMS4yODEtMC4xMjUgMi4yMzQtMC45ODR0MS4yMzQtMi4xNDFxMC40MDYtMS44MTMgMC40ODQtMy43NXQwLjA3OC0zLjgxMy0wLjA2My0zLjgxMy0wLjUtMy43NXYwek0xMS44NzUgMjEuMzc1di0xMC41OTRxMS4yODEgMC42NTYgMi41MzEgMS4zNDQgMS4yODEgMC42NTYgMi41NDcgMS4zMTN0Mi41NDcgMS4zMTNxMS4yNSAwLjY4OCAyLjUzMSAxLjM0NC0xLjI1IDAuNjU2LTIuNTMxIDEuMzEzdC0yLjU0NyAxLjMxMy0yLjU0NyAxLjM0NHEtMS4yNSAwLjY1Ni0yLjUzMSAxLjMxM3YweiI+PC9wYXRoPgo8L3N2Zz4K","text":"","iconSize":{"Desktop":{"point":"","unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-oY7DN4","url":"#","ariaLabel":"Follow instagram","icon":"fab fa-instagram","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTIyNC4xIDE0MWMtNjMuNiAwLTExNC45IDUxLjMtMTE0LjkgMTE0LjlzNTEuMyAxMTQuOSAxMTQuOSAxMTQuOVMzMzkgMzE5LjUgMzM5IDI1NS45IDI4Ny43IDE0MSAyMjQuMSAxNDF6bTAgMTg5LjZjLTQxLjEgMC03NC43LTMzLjUtNzQuNy03NC43czMzLjUtNzQuNyA3NC43LTc0LjcgNzQuNyAzMy41IDc0LjcgNzQuNy0zMy42IDc0LjctNzQuNyA3NC43em0xNDYuNC0xOTQuM2MwIDE0LjktMTIgMjYuOC0yNi44IDI2LjgtMTQuOSAwLTI2LjgtMTItMjYuOC0yNi44czEyLTI2LjggMjYuOC0yNi44IDI2LjggMTIgMjYuOCAyNi44em03Ni4xIDI3LjJjLTEuNy0zNS45LTkuOS02Ny43LTM2LjItOTMuOS0yNi4yLTI2LjItNTgtMzQuNC05My45LTM2LjItMzctMi4xLTE0Ny45LTIuMS0xODQuOSAwLTM1LjggMS43LTY3LjYgOS45LTkzLjkgMzYuMXMtMzQuNCA1OC0zNi4yIDkzLjljLTIuMSAzNy0yLjEgMTQ3LjkgMCAxODQuOSAxLjcgMzUuOSA5LjkgNjcuNyAzNi4yIDkzLjlzNTggMzQuNCA5My45IDM2LjJjMzcgMi4xIDE0Ny45IDIuMSAxODQuOSAwIDM1LjktMS43IDY3LjctOS45IDkzLjktMzYuMiAyNi4yLTI2LjIgMzQuNC01OCAzNi4yLTkzLjkgMi4xLTM3IDIuMS0xNDcuOCAwLTE4NC44ek0zOTguOCAzODhjLTcuOCAxOS42LTIyLjkgMzQuNy00Mi42IDQyLjYtMjkuNSAxMS43LTk5LjUgOS0xMzIuMSA5cy0xMDIuNyAyLjYtMTMyLjEtOWMtMTkuNi03LjgtMzQuNy0yMi45LTQyLjYtNDIuNi0xMS43LTI5LjUtOS05OS41LTktMTMyLjFzLTIuNi0xMDIuNyA5LTEzMi4xYzcuOC0xOS42IDIyLjktMzQuNyA0Mi42LTQyLjYgMjkuNS0xMS43IDk5LjUtOSAxMzIuMS05czEwMi43LTIuNiAxMzIuMSA5YzE5LjYgNy44IDM0LjcgMjIuOSA0Mi42IDQyLjYgMTEuNyAyOS41IDkgOTkuNSA5IDEzMi4xczIuNyAxMDIuNy05IDEzMi4xeiIvPjwvc3ZnPg==","text":"","iconSize":{"Desktop":{"point":"","unit":"px"}}} /-->
<!-- /wp:gutenverse/social-icons -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":"50","Mobile":null},"elementId":"guten-7jshxz","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px"},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"40","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-ObxZkq","content":"Information","color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-r2GHcB","spaceBetween":{"Desktop":"24"},"iconColor":{"type":"variable","id":"gv-color-primary"},"textColor":{"type":"variable","id":"gv-color-white"},"textColorHover":{"type":"variable","id":"gv-color-primary"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px"}}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-v4x3kU","url":"#","hasGlobalLink":true,"icon":"fas fa-chevron-right","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxMC42IDIzMy40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0xOTIgMTkyYy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMHMtMTIuNS0zMi44IDAtNDUuM0wyNDIuNyAyNTYgNzMuNCA4Ni42Yy0xMi41LTEyLjUtMTIuNS0zMi44IDAtNDUuM3MzMi44LTEyLjUgNDUuMyAwbDE5MiAxOTJ6Ii8+PC9zdmc+","text":"About Us","margin":{"Mobile":[]},"padding":{"Mobile":[]}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-wjo037","url":"#","hasGlobalLink":true,"icon":"fas fa-chevron-right","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxMC42IDIzMy40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0xOTIgMTkyYy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMHMtMTIuNS0zMi44IDAtNDUuM0wyNDIuNyAyNTYgNzMuNCA4Ni42Yy0xMi41LTEyLjUtMTIuNS0zMi44IDAtNDUuM3MzMi44LTEyLjUgNDUuMyAwbDE5MiAxOTJ6Ii8+PC9zdmc+","text":"Services"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-CXJE9X","url":"#","hasGlobalLink":true,"icon":"fas fa-chevron-right","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxMC42IDIzMy40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0xOTIgMTkyYy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMHMtMTIuNS0zMi44IDAtNDUuM0wyNDIuNyAyNTYgNzMuNCA4Ni42Yy0xMi41LTEyLjUtMTIuNS0zMi44IDAtNDUuM3MzMi44LTEyLjUgNDUuMyAwbDE5MiAxOTJ6Ii8+PC9zdmc+","text":"FAQ"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-RCmwXn","url":"#","hasGlobalLink":true,"icon":"fas fa-chevron-right","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxMC42IDIzMy40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0xOTIgMTkyYy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMHMtMTIuNS0zMi44IDAtNDUuM0wyNDIuNyAyNTYgNzMuNCA4Ni42Yy0xMi41LTEyLjUtMTIuNS0zMi44IDAtNDUuM3MzMi44LTEyLjUgNDUuMyAwbDE5MiAxOTJ6Ii8+PC9zdmc+","text":"Contact"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":22.799999999999997,"Tablet":50,"Mobile":100},"elementId":"guten-GSdgKl","margin":{"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":""}},"Tablet":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-RwERkk","content":"Contact us","color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Mobile":[]},"padding":{"Mobile":[]}} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-skstzK","spaceBetween":{"Desktop":"36"},"verticalAlign":"flex-start","iconColor":{"type":"variable","id":"gv-color-primary"},"textColor":{"type":"variable","id":"gv-color-white"},"textColorHover":{"type":"variable","id":"gv-color-primary"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px"}}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-u4rgxR","icon":"fas fa-map-marker-alt","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzODQgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTIxNS43IDQ5OS4yQzI2NyA0MzUgMzg0IDI3OS40IDM4NCAxOTJDMzg0IDg2IDI5OCAwIDE5MiAwUzAgODYgMCAxOTJjMCA4Ny40IDExNyAyNDMgMTY4LjMgMzA3LjJjMTIuMyAxNS4zIDM1LjEgMTUuMyA0Ny40IDB6TTE5MiAxMjhhNjQgNjQgMCAxIDEgMCAxMjggNjQgNjQgMCAxIDEgMC0xMjh6Ii8+PC9zdmc+","text":"Jl. Sunset Road No.815, Kuta, Bali - 80361"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-TLw8Ss","icon":"fas fa-phone","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTE2NC45IDI0LjZjLTcuNy0xOC42LTI4LTI4LjUtNDcuNC0yMy4ybC04OCAyNEMxMi4xIDMwLjIgMCA0NiAwIDY0QzAgMzExLjQgMjAwLjYgNTEyIDQ0OCA1MTJjMTggMCAzMy44LTEyLjEgMzguNi0yOS41bDI0LTg4YzUuMy0xOS40LTQuNi0zOS43LTIzLjItNDcuNGwtOTYtNDBjLTE2LjMtNi44LTM1LjItMi4xLTQ2LjMgMTEuNkwzMDQuNyAzNjhDMjM0LjMgMzM0LjcgMTc3LjMgMjc3LjcgMTQ0IDIwNy4zTDE5My4zIDE2N2MxMy43LTExLjIgMTguNC0zMCAxMS42LTQ2LjNsLTQwLTk2eiIvPjwvc3ZnPg==","text":"(021) 231 - 2826"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-g9KKZJ","url":"#","hasGlobalLink":true,"icon":"fas fa-envelope","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQ4IDY0QzIxLjUgNjQgMCA4NS41IDAgMTEyYzAgMTUuMSA3LjEgMjkuMyAxOS4yIDM4LjRMMjM2LjggMzEzLjZjMTEuNCA4LjUgMjcgOC41IDM4LjQgMEw0OTIuOCAxNTAuNGMxMi4xLTkuMSAxOS4yLTIzLjMgMTkuMi0zOC40YzAtMjYuNS0yMS41LTQ4LTQ4LTQ4SDQ4ek0wIDE3NlYzODRjMCAzNS4zIDI4LjcgNjQgNjQgNjRINDQ4YzM1LjMgMCA2NC0yOC43IDY0LTY0VjE3NkwyOTQuNCAzMzkuMmMtMjIuOCAxNy4xLTU0IDE3LjEtNzYuOCAwTDAgMTc2eiIvPjwvc3ZnPg==","text":"example@example.com"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":32.2,"Tablet":50,"Mobile":100},"elementId":"guten-XiDd6I","margin":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-ormijW","content":"Work Hours","color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Gf9XrM","columns":{"Desktop":"1","Tablet":"1","Mobile":"1"},"alignment":{"Desktop":"left","Tablet":"left","Mobile":"left"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-lrG6rG","displayInline":true,"spaceBetween":{"Desktop":"32"},"iconColor":{"type":"variable","id":"gv-color-primary"},"textColor":{"type":"variable","id":"gv-color-white"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15","top":"10","right":"","left":""}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-sttAdL","ariaLabel":"hours","icon":"fas fa-clock","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTI1NiAwYTI1NiAyNTYgMCAxIDEgMCA1MTJBMjU2IDI1NiAwIDEgMSAyNTYgMHpNMjMyIDEyMFYyNTZjMCA4IDQgMTUuNSAxMC43IDIwbDk2IDY0YzExIDcuNCAyNS45IDQuNCAzMy4zLTYuN3M0LjQtMjUuOS02LjctMzMuM0wyODAgMjQzLjJWMTIwYzAtMTMuMy0xMC43LTI0LTI0LTI0cy0yNCAxMC43LTI0IDI0eiIvPjwvc3ZnPg==","text":"8 AM - 7 PM , Monday - Saturday","margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[]}} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Fjw4Jk","gap":{"Desktop":{"point":"101","unit":"px"}},"textColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"10"}}},"padding":{"Desktop":[]}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipisc elit, sed do eiusmod tempor incididunt </p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-8ssSjZ","content":"Call Us Today","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","left":"32","bottom":"18"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"gv-color-primary"},"ariaLabel":"direct to contact"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-ob9UeO","verticalAlign":"center","border":{"radius":{"Desktop":{"unit":"px"}},"top":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":0.1}}},"borderResponsive":{"Mobile":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"100","left":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"20","right":"0","bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":55,"Mobile":100},"elementId":"guten-iKOdkB","verticalAlign":{"Desktop":"default","Tablet":"default","Mobile":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-icotpe","columns":{"Desktop":"1","Tablet":""},"gap":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"alignment":{"Desktop":"left","Tablet":"left","Mobile":"center"},"textColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-white"},"linkTypography":{"lineHeight":{"Desktop":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":""}},"decoration":"underline"},"linkColorHover":{"type":"variable","id":"gv-color-accent-hover"},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[]}} -->
<!-- wp:paragraph -->
<p>Copyright © 2026. Built with <a href="https://gutenverse.com/?utm_source=financio&amp;utm_medium=footer" data-type="link" data-id="https://gutenverse.com/?utm_source=financio&amp;utm_medium=footer" target="_blank" rel="noreferrer noopener">Gutenverse</a> FInance theme.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":100,"Tablet":45},"elementId":"guten-GPSwAp","verticalAlign":{"Desktop":"center"}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-uB4Kcu","displayInline":true,"spaceBetween":{"Desktop":"32","Tablet":""},"alignList":{"Desktop":"flex-end","Mobile":"center"},"iconColor":{"type":"variable","id":"gv-color-white"},"textColor":{"type":"variable","id":"gv-color-white"},"textColorHover":{"type":"variable","id":"gv-color-primary"},"textTypography":{"type":"variable","id":"gv-font-meta-secondary","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"border":{"radius":{"unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"default"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-tG1o1w","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Terms Of Service"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-gvbyGv","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Privacy Policy"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-cQJAYR","url":"#","hasGlobalLink":true,"hideIcon":true,"text":"Legal"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
